name: Lint

on:
    pull_request:
        branches: ["**"]

jobs:
    lint:
        runs-on: ubuntu-latest
        steps:
            - name: Set up Github Workspace
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0
            - name: Set up Python Environment 3.11
              uses: actions/setup-python@v4
              with:
                  python-version: 3.11
            - name: Install Python Dependencies
              run: |
                  python -m pip install --upgrade pip
                  python -m pip install -q hatch pre-commit
                  hatch env create
                  hatch --version
            - name: Lint
              id: lint
              continue-on-error: true
              run: |
                  hatch run lint:style
            - name: Type Checking
              id: check
              continue-on-error: true
              run: |
                  hatch run lint:typing
            - name: Raise Errors For Linting Failures
              if: |
                  steps.lint.outcome != 'success'
              # TODO: and steps.check.outcome != 'success'
              run: |
                  echo "Lint: ${{ steps.lint.outcome }}"
                  echo "Check: ${{ steps.check.outcome }}"
                  exit 1
