name: Tests

on:
    pull_request:
        branches: ["**"]
        paths:
            - app/**
            - pyproject.toml
            - .github/workflows/tests.yaml
jobs:
    test-suite:
        runs-on: ubuntu-latest
        strategy:
            fail-fast: true
            matrix:
                include:
                    - { name: Python 3.11, python: "3.11" }
                    - { name: Python 3.10, python: "3.10" }
                    - { name: Python 3.9, python: "3.9" }
                    - { name: Python 3.8, python: "3.8" }
        concurrency:
            group: ${{ github.workflow }}-${{ matrix.python }}-${{ github.ref }}
            cancel-in-progress: true
        steps:
            - name: Set up Github Workspace
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0
            - name: Set up Python Environment ${{ matrix.python }}
              uses: actions/setup-python@v4
              with:
                  python-version: ${{ matrix.python }}
            - name: Install Hatch
              run: |
                  python -m pip install --upgrade pip
                  python -m pip install -q hatch pre-commit
                  hatch --version
            - name: Test Suite
              run: |
                  hatch run +py="${{ matrix.python }}" all:cov
